# Generated by Django 3.1 on 2020-11-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='diagram1',
            field=models.ImageField(blank=True, null=True, upload_to='question_images'),
        ),
    ]
