# Generated by Django 3.1 on 2021-01-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201102_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('nos', models.IntegerField(default=0)),
                ('noq', models.IntegerField(default=0)),
                ('tm', models.IntegerField(default=0)),
                ('mark_array', models.CharField(default='', max_length=200)),
                ('question_array', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
